protected/models/Drawing.php
<?php

/**
 * This is the model class for table "drawing".
 *
 * The followings are the available columns in table 'drawing':
 * @property integer $id
 * @property integer $project_id
 * @property string $name
 * @property string $type
 * @property string $detail
 * @property string $date
 * @property string $pic
 *
 * The followings are the available model relations:
 * @property Project $project
 */
class Drawing extends CActiveRecord
{
	/**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return Drawing the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'drawing';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('project_id, name, date', 'required'),
			array('project_id', 'numerical', 'integerOnly'=>true),
			array('name, type, pic', 'length', 'max'=>128),
			array('detail', 'safe'),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('id, project_id, name, type, detail, date, pic', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'project' => array(self::BELONGS_TO, 'Project', 'project_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'project_id' => 'Project',
			'name' => 'Name',
			'type' => 'Type',
			'detail' => 'Detail',
			'date' => 'Date',
			'pic' => 'Pic',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('project_id',$this->project_id);
		$criteria->compare('name',$this->name,true);
		$criteria->compare('type',$this->type,true);
		$criteria->compare('detail',$this->detail,true);
		$criteria->compare('date',$this->date,true);
		$criteria->compare('pic',$this->pic,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}
}

protected/controllers/DrawingController.php
<?php

class DrawingController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update','admin','delete'),
				'users'=>array('@'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$id = Yii::app()->session['project'];
		$model=new Drawing;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Drawing']))
		{
			$model->attributes=$_POST['Drawing'];
			$model->project_id = $id;
			if($model->save())
				$this->redirect(array('index','id'=>$id));
		} else {
			$model->date = date('Y-m-d');
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Drawing']))
		{
			$model->attributes=$_POST['Drawing'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$id = Yii::app()->session['project'];
		$dataProvider=new CActiveDataProvider('Drawing', array(
			'criteria' => array(
				'condition'=>'project_id=:id',
				'params'=>array(':id'=>$id),
			),
		));
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
			'id'=>$id,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Drawing('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Drawing']))
			$model->attributes=$_GET['Drawing'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Drawing::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='drawing-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/drawing/_form.php
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
	'id'=>'drawing-form',
	'enableAjaxValidation'=>false,
)); ?>

	<p class="help-block">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<?php echo $form->textFieldRow($model,'name',array('class'=>'span6','maxlength'=>128)); ?>

	<?php echo $form->textFieldRow($model,'type',array('class'=>'span6','maxlength'=>128)); ?>

	<?php echo $form->textAreaRow($model,'detail',array('rows'=>6, 'cols'=>50, 'class'=>'ckeditor span6')); ?>

	<?php echo $form->textFieldRow($model,'pic',array('class'=>'span6','maxlength'=>128, 'id'=>'pics')); ?>
	<a href="#" class="btn btn-primary" onclick="openKCFinder_singleFile()">Browse Server</a>

	<?php echo $form->textFieldRow($model,'date',array('class'=>'span6')); ?>

	<div class="form-actions">
		<?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType'=>'submit',
			'type'=>'primary',
			'label'=>$model->isNewRecord ? 'Create' : 'Save',
		)); ?>
	</div>

<?php $this->endWidget(); ?>

<?php $this->renderPartial('//layouts/ckeditor') ?>
<?php $this->renderPartial('//layouts/kcfinder') ?>

protected/views/drawing/_search.php
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<?php echo $form->textFieldRow($model,'id',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'project_id',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'name',array('class'=>'span5','maxlength'=>128)); ?>

	<?php echo $form->textFieldRow($model,'type',array('class'=>'span5','maxlength'=>128)); ?>

	<?php echo $form->textAreaRow($model,'detail',array('rows'=>6, 'cols'=>50, 'class'=>'span8')); ?>

	<?php echo $form->textFieldRow($model,'date',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'pic',array('class'=>'span5','maxlength'=>128)); ?>

	<div class="form-actions">
		<?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType'=>'submit',
			'type'=>'primary',
			'label'=>'Search',
		)); ?>
	</div>

<?php $this->endWidget(); ?>

protected/views/drawing/_view.php
<div class="span3">

	<?php echo CHtml::image($data->pic); ?>

	<b><?php echo CHtml::link(CHtml::encode($data->name), array('/drawing/view', 'id'=>$data->id)); ?></b> <br />
	<?php echo CHtml::encode($data->type); ?> <br />
	<?php echo CHtml::encode($data->date); ?> <br />
	<?php echo $data->detail; ?> <br />
</div>

protected/views/drawing/admin.php
<?php
$this->breadcrumbs=array(
	'Drawings'=>array('index'),
	'Manage',
);

$this->menu=array(
	array('label'=>'List Drawing','url'=>array('index')),
	array('label'=>'Create Drawing','url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('drawing-grid', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Manage Drawings</h1>

<p>
You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.
</p>

<?php echo CHtml::link('Advanced Search','#',array('class'=>'search-button btn')); ?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('bootstrap.widgets.TbGridView',array(
	'id'=>'drawing-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		'id',
		'project_id',
		'name',
		'type',
		'detail',
		'date',
		/*
		'pic',
		*/
		array(
			'class'=>'bootstrap.widgets.TbButtonColumn',
		),
	),
)); ?>

protected/views/drawing/create.php
<?php
$this->breadcrumbs=array(
	'Drawings'=>array('index'),
	'Create',
);

$this->menu=array(
	array('label'=>'List Drawing','url'=>array('index')),
	array('label'=>'Manage Drawing','url'=>array('admin')),
);
?>

<h1>Create Drawing</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/drawing/index.php
<?php
$this->menu=array(
	array('label'=>'Create Drawing','url'=>array('create','id'=>$id)),
	array('label'=>'Manage Drawing','url'=>array('admin')),
);
?>

<?php $this->renderPartial('//project/toolbar', array('model'=>Project::model()->findByPk($id))); ?>

<h1>Drawings</h1>

<div class="row">
<?php $this->widget('bootstrap.widgets.TbListView',array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>
</div>

protected/views/drawing/update.php
<?php
$this->breadcrumbs=array(
	'Drawings'=>array('index'),
	$model->name=>array('view','id'=>$model->id),
	'Update',
);

$this->menu=array(
	array('label'=>'List Drawing','url'=>array('index')),
	array('label'=>'Create Drawing','url'=>array('create')),
	array('label'=>'View Drawing','url'=>array('view','id'=>$model->id)),
	array('label'=>'Manage Drawing','url'=>array('admin')),
);
?>

<h1>Update Drawing <?php echo $model->id; ?></h1>

<?php echo $this->renderPartial('_form',array('model'=>$model)); ?>

protected/views/drawing/view.php
<?php
$this->breadcrumbs=array(
	'Drawing'=>array('index'),
	$model->name,
);

?>

<h1><?php echo $model->name; ?></h1>

<?php echo CHtml::image($model->pic); ?>